[package]
name = "noveltui"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
color-eyre = "0.6.5"
crossterm = "0.29.0"
once_cell = "1.21.3"
ratatui = "0.29.0"
regex = "1.12.2"
textwrap = "0.16.2"
